spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/vueblog2?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #其他druid配置
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 25
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  #redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 100s
  cache:
   redis:
     time-to-live: -1
  thymeleaf:
    cache: false

server:
  port: 8081

logging:
  path: C:/Users/Administrator/IdeaProjects/myblogserver2/
  level:
    com.example.mapper: debug

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml