spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/vueblog2?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

server:
  port: 8081

logging:
  path: C:/Users/Administrator/IdeaProjects/myblogserver2/
  level:
    com.example.mapper: debug

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml