spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1000s
    jedis:
      pool:
        max-idle: 8
        min-idle: 3
        max-wait: -1
        max-active: -1
  cache:
    redis:
      time-to-live: -1

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.example.mapper: debug
  path: D:\studyJava\ideaProject\springboot-redis\